services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-server
    ports:
      - "8025:8000"
    volumes:
      - ./chroma_data:/data
    restart: always

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: always
