FROM oven/bun:1.3.14-alpine

WORKDIR /app

COPY package.json bun.lock ./

RUN bun install --frozen-lockfile

COPY . .

# Tạo thư mục chứa dữ liệu JWT
RUN mkdir -p /app/data

# Start the proxy
CMD ["bun", "./src/dynamic-proxy.ts"]
