FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install -g npm@latest
RUN npm install

# Vá lại các lỗi/lỗ hổng package nếu có
RUN npm audit fix

COPY . .

# Start the proxy
CMD ["npx", "tsx", "./src/dynamic-proxy.ts"]